# Generated by Django 2.1.2 on 2018-12-28 23:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxer_1', models.CharField(max_length=100)),
                ('boxer_2', models.CharField(max_length=100)),
                ('result', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(verbose_name=datetime.datetime(2018, 12, 28, 23, 4, 58, 76858))),
                ('time_finished', models.DateTimeField(blank=True)),
                ('round_1', models.CharField(max_length=25)),
                ('round_2', models.CharField(max_length=25)),
                ('round_3', models.CharField(max_length=25)),
                ('round_4', models.CharField(max_length=25)),
                ('round_5', models.CharField(max_length=25)),
                ('round_6', models.CharField(max_length=25)),
                ('round_7', models.CharField(max_length=25)),
                ('round_8', models.CharField(max_length=25)),
                ('round_9', models.CharField(max_length=25)),
                ('round_10', models.CharField(max_length=25)),
                ('round_11', models.CharField(max_length=25)),
                ('round_12', models.CharField(max_length=25)),
                ('fight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Fight')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
