# Generated by Django 2.1.2 on 2019-01-11 16:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxer_1', models.CharField(max_length=100)),
                ('boxer_2', models.CharField(max_length=100)),
                ('fight_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 11, 16, 44, 21, 833512))),
                ('time_finished', models.DateTimeField(blank=True, null=True)),
                ('fight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Fight')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('boxer_1_hits', models.IntegerField(blank=True, null=True)),
                ('boxer_1_knockdowns', models.IntegerField(blank=True, null=True)),
                ('boxer_1_penalties', models.IntegerField(blank=True, null=True)),
                ('boxer_2_hits', models.IntegerField(blank=True, null=True)),
                ('boxer_2_knockdowns', models.IntegerField(blank=True, null=True)),
                ('boxer_2_penalties', models.IntegerField(blank=True, null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
    ]
