# Generated by Django 2.1.2 on 2019-01-10 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='fight_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 10, 13, 44, 50, 76511)),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
