# Generated by Django 2.1.2 on 2019-01-29 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 29, 20, 8, 57, 874256)),
        ),
    ]
