# Generated by Django 2.1.2 on 2018-12-28 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 12, 28, 23, 14, 42, 674279)),
        ),
    ]
