# Generated by Django 2.1.2 on 2018-12-28 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20181228_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 12, 28, 23, 15, 27, 938185)),
        ),
    ]
