# Generated by Django 2.1.2 on 2019-01-10 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190110_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('boxer_1_hits', models.IntegerField(blank=True, null=True)),
                ('boxer_1_knockdowns', models.IntegerField(blank=True, null=True)),
                ('boxer_1_penalties', models.IntegerField(blank=True, null=True)),
                ('boxer_2_hits', models.IntegerField(blank=True, null=True)),
                ('boxer_2_knockdowns', models.IntegerField(blank=True, null=True)),
                ('boxer_2_penalties', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_10',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_11',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_12',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_8',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_9',
        ),
        migrations.AlterField(
            model_name='game',
            name='time_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 10, 16, 12, 2, 129748)),
        ),
        migrations.AddField(
            model_name='round',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
