# Generated by Django 2.1.5 on 2019-01-30 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190129_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 30, 10, 54, 50, 551478)),
        ),
    ]
