# Generated by Django 2.1.2 on 2018-12-28 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20181228_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='result',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 12, 28, 23, 18, 3, 346248)),
        ),
    ]
